sudo: required

service:
    - docker

before_install:
    - docker build -t soumya9v/react-test -f ./client/Dockerfile.dev ./client

# if travis return other than 0 means error in script
script:
    - docker run -e CI=true soumya9v/react-test npm run test -- --coverage

after_success:
    - docker build -t soumya9v/multi-client  ./client
    - docker build -t soumya9v/multi-nginx  ./nginx
    - docker build -t soumya9v/multi-server  ./server
    - docker build -t soumya9v/multi-worker  ./worker

    # Log in to the docker CLI
    # Go to travis-ci --> project --> settings
    # Environment Variables --> provide DOCKER_ID and DOCKER_PASSWORD
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push to docker hub
    - docker push soumya9v/multi-client
    - docker push soumya9v/multi-nginx
    - docker push soumya9v/multi-server
    - docker push soumya9v/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2 # from url generated by ews
    app: multi-docker
    env: MultiDocker-env
    #from s3 Bucket in services
    #Attach existing policies directly
    bucket_name: elasticbeanstalk-us-east-2-961749170280
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY #iam service (Identity and access manager)
    secret_access_key: $AWS_SECRET_KEY
